// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzmbEah_RWUJNE70xBUJa-pmq_-KGuaE4',
    appId: '1:349461823789:web:383dfcbae4852c689e93a4',
    messagingSenderId: '349461823789',
    projectId: 'evaluacionfinal-b9fce',
    authDomain: 'evaluacionfinal-b9fce.firebaseapp.com',
    storageBucket: 'evaluacionfinal-b9fce.firebasestorage.app',
    measurementId: 'G-79SV6ZC83K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaG6V0zKJBXTTmqIvLlkJ1v5pI2ZdVZB0',
    appId: '1:349461823789:android:2440b75d12b2e8829e93a4',
    messagingSenderId: '349461823789',
    projectId: 'evaluacionfinal-b9fce',
    storageBucket: 'evaluacionfinal-b9fce.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzmbEah_RWUJNE70xBUJa-pmq_-KGuaE4',
    appId: '1:349461823789:web:c035063a1b7bf8c89e93a4',
    messagingSenderId: '349461823789',
    projectId: 'evaluacionfinal-b9fce',
    authDomain: 'evaluacionfinal-b9fce.firebaseapp.com',
    storageBucket: 'evaluacionfinal-b9fce.firebasestorage.app',
    measurementId: 'G-X0EMDV7EF2',
  );
}
